baseURL = "https://blog.sanmarcsoft.com/"
title = "SanMarcSoft Blog"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
  pagerSize = 20

[params]
  author = "Matthew Stevens"
  info = "SanmarcSoft LLC"
  description = "From Code to Prose"
  keywords = "blog,developer,personal"
  avatarURL = "https://www.gravatar.com/avatar/3635ab3e26ed90749ab2aa3ca1ebc4ca?s=80"
  colorScheme = "auto"
  customCSS = ["scss/custom.scss"]
  
  # Social links
  [[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/yourusername/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[module]
  [module.hugoVersion]
    min = "0.124.0"
