name: Deploy to S3

    on:
      push:
        branches:
          - main

    jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18' # Or your preferred Node.js version

          - name: Install dart-sass
            run: npm install -g sass

          - name: Verify dart-sass
            run: |
              which sass
              ls -l $(which sass)
              sass --version

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
              hugo-version: '0.145.0'
              extended: true

          - name: Build Hugo site
            run: hugo

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-north-1

          - name: Deploy to S3
            run: |
              aws s3 sync public/ s3://blog-sanmarcsoft-com --delete
    ```

2.  **Verify Hugo Configuration:**
    * The hugo build step is failing, because it cannot find the configuration files.
    * This is likely, because the build step is running in the wrong directory.
    * Add a `cd` command to the build hugo site step.
    * Modify the hugo build step to this:

```yaml
    - name: Build Hugo site
      run: |
        cd ./
        hugo
