name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dart-sass
        run: |
          sudo snap install dart-sass
          which sass
          sass --version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0' # or 'latest'

      - name: Build Hugo site
        run: |
          cd ./
          echo "PATH: $PATH"
          echo "snap bin directory: /snap/bin"
          ls -l /snap/bin
          hugo --minify --baseURL "https://blog.sanmarcsoft.com/"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync public/ s3://blog-sanmarcsoft-com --delete
