name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dart-sass and set path
        run: |
          sudo apt-get update
          sudo apt-get install -y sass
          sudo apt-get remove -y ruby-sass
          echo "dart-sass installed successfully"
          echo "PATH=$PATH:/usr/bin" >> $GITHUB_ENV #Add /usr/bin to the system path.
          sass --version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build Hugo site
        run: hugo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync public/ s3://blog-sanmarcsoft-com --delete
